/*
 * smk_autogen.c — functions produced by tools/recomp/autogen.py + batch.py from
 * ROM bytes + trace-exact entry M/X flags, each gated BYTE-IDENTICAL to the
 * emulation oracle THROUGH A RACE via tools/diff_snapshots.py.
 *
 * Regenerate: py tools/recomp/batch.py "<rom>.sfc" <prof.txt> <tmp.c>, then wrap
 * with this header (the link anchor must stay).
 */
#include "smk/functions.h"
#include <snesrecomp/snesrecomp.h>
#include <snesrecomp/func_table.h>
#include <stdint.h>

/* Link anchor: forces this static-lib TU (and its RECOMP_PATCH registrations) to
 * link; main() calls it once. Without it the linker drops the whole object. */
void smk_autogen_link_anchor(void) {}

/* Auto-generated by tools/recomp/autogen.py from $80:F90A
 * entry M=0 X=0 (P=$00). Validate with the diff harness. */
RECOMP_PATCH(smk_80F90A, 0x80F90A) {
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0x5A + g_cpu.X))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $F90A LDA */
    { uint16_t _x = (uint16_t)(g_cpu.C); uint8_t _c = (uint8_t)((_x >> 15) & 1); uint16_t _r = (uint16_t)(_x << 1); g_cpu.flag_C = _c; g_cpu.C = (uint16_t)((_r) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_r) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_r) == 0); } /* $F90C ASL */
    if (g_cpu.flag_C) goto L_F927;  /* $F90D BCS */
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0x5E + g_cpu.X))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $F90F LDA */
    if (!g_cpu.flag_Z) goto L_F924;  /* $F911 BNE */
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0x5C + g_cpu.X))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $F913 LDA */
    if (g_cpu.flag_Z) goto L_F91C;  /* $F915 BEQ */
    { uint16_t _t = (uint16_t)((g_cpu.C) - 1); g_cpu.C = (uint16_t)((_t) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_t) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_t) == 0); } /* $F917 DEC */
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x5C + g_cpu.X), (uint16_t)(g_cpu.C)); /* $F918 STA */
    goto L_F927;   /* $F91A BRA */
  L_F91C:;
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0x10 + g_cpu.X))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $F91C LDA */
    { uint16_t _a = (uint16_t)(g_cpu.C); uint16_t _v = (uint16_t)(0xBFFF); _a = (uint16_t)(_a & _v); g_cpu.C = (uint16_t)((_a) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_a) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_a) == 0); } /* $F91E AND */
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x10 + g_cpu.X), (uint16_t)(g_cpu.C)); /* $F921 STA */
    return;            /* $F923 RTS */
  L_F924:;
    { uint16_t _t = (uint16_t)((g_cpu.C) - 1); g_cpu.C = (uint16_t)((_t) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_t) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_t) == 0); } /* $F924 DEC */
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x5E + g_cpu.X), (uint16_t)(g_cpu.C)); /* $F925 STA */
  L_F927:;
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0x10 + g_cpu.X))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $F927 LDA */
    { uint16_t _a = (uint16_t)(g_cpu.C); uint16_t _v = (uint16_t)(0x4000); _a = (uint16_t)(_a | _v); g_cpu.C = (uint16_t)((_a) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_a) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_a) == 0); } /* $F929 ORA */
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x10 + g_cpu.X), (uint16_t)(g_cpu.C)); /* $F92C STA */
    g_cpu.flag_C = 1;                              /* $F92E SEC */
    return;            /* $F92F RTS */
}

/* Auto-generated by tools/recomp/autogen.py from $80:A01F
 * entry M=0 X=0 (P=$00). Validate with the diff harness. */
RECOMP_PATCH(smk_80A01F, 0x80A01F) {
    op_phx16();                                    /* $A01F PHX */
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0xE6 + g_cpu.X))); g_cpu.Y = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $A020 LDY */
    func_table_call_jsr(0x80A027);                 /* $A022 JSR $80A027 */
    op_plx16();                                    /* $A025 PLX */
    return;            /* $A026 RTS */
}

/* Auto-generated by tools/recomp/autogen.py from $80:A027
 * entry M=0 X=0 (P=$00). Validate with the diff harness. */
RECOMP_PATCH(smk_80A027, 0x80A027) {
  L_A027:;
    { uint16_t _a = (uint16_t)(g_cpu.Y); uint16_t _v = (uint16_t)(0x0000); uint16_t _t = (uint16_t)(_a - _v); g_cpu.flag_C = (uint8_t)(_a >= _v); g_cpu.flag_Z = (uint8_t)(_a == _v); g_cpu.flag_N = (uint8_t)((_t >> 15) & 1); } /* $A027 CPY */
    if (g_cpu.flag_Z) goto L_A05B;  /* $A02A BEQ */
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x010E + g_cpu.Y))); g_cpu.X = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $A02C LDX */
    if (g_cpu.flag_Z) goto L_A05B;  /* $A02F BEQ */
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0xC0 + g_cpu.X))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $A031 LDA */
    op_phx16();                                    /* $A033 PHX */
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x010C + g_cpu.Y))); g_cpu.X = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $A034 LDX */
    if (g_cpu.flag_Z) goto L_A05A;  /* $A037 BEQ */
    { uint16_t _a = (uint16_t)(g_cpu.C); uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0xC0 + g_cpu.X))); uint16_t _t = (uint16_t)(_a - _v); g_cpu.flag_C = (uint8_t)(_a >= _v); g_cpu.flag_Z = (uint8_t)(_a == _v); g_cpu.flag_N = (uint8_t)((_t >> 15) & 1); } /* $A039 CMP */
    if (g_cpu.flag_Z) goto L_A05A;  /* $A03B BEQ */
    if (!g_cpu.flag_C) goto L_A05A;  /* $A03D BCC */
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0x10 + g_cpu.X))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $A03F LDA */
    g_cpu.flag_Z = (uint8_t)(((uint16_t)(g_cpu.C) & (uint16_t)0x0020) == 0); /* $A041 BIT */
    if (!g_cpu.flag_Z) goto L_A05A;  /* $A044 BNE */
    op_txa();                                      /* $A046 TXA */
    bus_write16(g_cpu.DB, (uint16_t)(0x010E + g_cpu.Y), (uint16_t)(g_cpu.C)); /* $A047 STA */
    op_tya();                                      /* $A04A TYA */
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0xE6 + g_cpu.X), (uint16_t)(g_cpu.C)); /* $A04B STA */
    op_plx16();                                    /* $A04D PLX */
    op_txa();                                      /* $A04E TXA */
    bus_write16(g_cpu.DB, (uint16_t)(0x010C + g_cpu.Y), (uint16_t)(g_cpu.C)); /* $A04F STA */
    op_tya();                                      /* $A052 TYA */
    { uint16_t _t = (uint16_t)((g_cpu.C) - 1); g_cpu.C = (uint16_t)((_t) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_t) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_t) == 0); } /* $A053 DEC */
    { uint16_t _t = (uint16_t)((g_cpu.C) - 1); g_cpu.C = (uint16_t)((_t) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_t) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_t) == 0); } /* $A054 DEC */
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0xE6 + g_cpu.X), (uint16_t)(g_cpu.C)); /* $A055 STA */
    op_tay();                                      /* $A057 TAY */
    goto L_A027;   /* $A058 BRA */
  L_A05A:;
    op_plx16();                                    /* $A05A PLX */
  L_A05B:;
    return;            /* $A05B RTS */
}

/* Auto-generated by tools/recomp/autogen.py from $81:8902
 * entry M=0 X=0 (P=$00). Validate with the diff harness. */
RECOMP_PATCH(smk_818902, 0x818902) {
    op_sep(0x30);                                  /* $8902 SEP */
    { uint8_t _m = (uint8_t)(bus_read8(g_cpu.DB, 0x1F06)); uint8_t _a = (uint8_t)((uint8_t)(g_cpu.C & 0xFF)); g_cpu.flag_Z = (uint8_t)((_a & _m) == 0); g_cpu.flag_N = (uint8_t)((_m >> 7) & 1); g_cpu.flag_V = (uint8_t)((_m >> 6) & 1); } /* $8904 BIT */
    if (!g_cpu.flag_N) goto L_8918;  /* $8907 BPL */
    { uint8_t _v = (uint8_t)(0x08); g_cpu.C = (uint16_t)((g_cpu.C & 0xFF00) | ((_v) & 0xFF)); g_cpu.flag_N = (uint8_t)(((uint8_t)(_v) >> 7) & 1); g_cpu.flag_Z = (uint8_t)((uint8_t)(_v) == 0); } /* $8909 LDA */
    bus_write8(g_cpu.DB, 0x2100, (uint8_t)((uint8_t)(g_cpu.C & 0xFF))); /* $890B STA */
    { uint8_t _v = (uint8_t)(0x10); g_cpu.X = (uint16_t)((_v) & 0xFF); g_cpu.flag_N = (uint8_t)(((uint8_t)(_v) >> 7) & 1); g_cpu.flag_Z = (uint8_t)((uint8_t)(_v) == 0); } /* $890E LDX */
  L_8910:;
    { uint8_t _t = (uint8_t)(((uint8_t)(g_cpu.X & 0xFF)) - 1); g_cpu.X = (uint16_t)((_t) & 0xFF); g_cpu.flag_N = (uint8_t)(((uint8_t)(_t) >> 7) & 1); g_cpu.flag_Z = (uint8_t)((uint8_t)(_t) == 0); } /* $8910 DEX */
    if (!g_cpu.flag_Z) goto L_8910;  /* $8911 BNE */
    { uint8_t _v = (uint8_t)(0x0F); g_cpu.C = (uint16_t)((g_cpu.C & 0xFF00) | ((_v) & 0xFF)); g_cpu.flag_N = (uint8_t)(((uint8_t)(_v) >> 7) & 1); g_cpu.flag_Z = (uint8_t)((uint8_t)(_v) == 0); } /* $8913 LDA */
    bus_write8(g_cpu.DB, 0x2100, (uint8_t)((uint8_t)(g_cpu.C & 0xFF))); /* $8915 STA */
  L_8918:;
    op_rep(0x30);                                  /* $8918 REP */
    return;            /* $891A RTS */
}

/* Auto-generated by tools/recomp/autogen.py from $81:B9A8
 * entry M=1 X=0 (P=$20). Validate with the diff harness. */
RECOMP_PATCH(smk_81B9A8, 0x81B9A8) {
    { uint8_t _v = (uint8_t)(bus_read8(g_cpu.DB, (uint16_t)(0x0000 + g_cpu.Y))); g_cpu.C = (uint16_t)((g_cpu.C & 0xFF00) | ((_v) & 0xFF)); g_cpu.flag_N = (uint8_t)(((uint8_t)(_v) >> 7) & 1); g_cpu.flag_Z = (uint8_t)((uint8_t)(_v) == 0); } /* $B9A8 LDA */
    { uint8_t _x = (uint8_t)((uint8_t)(g_cpu.C & 0xFF)); uint8_t _c = (uint8_t)(_x & 1); uint8_t _r = (uint8_t)(_x >> 1); g_cpu.flag_C = _c; g_cpu.C = (uint16_t)((g_cpu.C & 0xFF00) | ((_r) & 0xFF)); g_cpu.flag_N = (uint8_t)(((uint8_t)(_r) >> 7) & 1); g_cpu.flag_Z = (uint8_t)((uint8_t)(_r) == 0); } /* $B9AB LSR */
    { uint8_t _x = (uint8_t)((uint8_t)(g_cpu.C & 0xFF)); uint8_t _c = (uint8_t)(_x & 1); uint8_t _r = (uint8_t)(_x >> 1); g_cpu.flag_C = _c; g_cpu.C = (uint16_t)((g_cpu.C & 0xFF00) | ((_r) & 0xFF)); g_cpu.flag_N = (uint8_t)(((uint8_t)(_r) >> 7) & 1); g_cpu.flag_Z = (uint8_t)((uint8_t)(_r) == 0); } /* $B9AC LSR */
    { uint8_t _x = (uint8_t)((uint8_t)(g_cpu.C & 0xFF)); uint8_t _c = (uint8_t)(_x & 1); uint8_t _r = (uint8_t)(_x >> 1); g_cpu.flag_C = _c; g_cpu.C = (uint16_t)((g_cpu.C & 0xFF00) | ((_r) & 0xFF)); g_cpu.flag_N = (uint8_t)(((uint8_t)(_r) >> 7) & 1); g_cpu.flag_Z = (uint8_t)((uint8_t)(_r) == 0); } /* $B9AD LSR */
    { uint8_t _x = (uint8_t)((uint8_t)(g_cpu.C & 0xFF)); uint8_t _c = (uint8_t)(_x & 1); uint8_t _r = (uint8_t)(_x >> 1); g_cpu.flag_C = _c; g_cpu.C = (uint16_t)((g_cpu.C & 0xFF00) | ((_r) & 0xFF)); g_cpu.flag_N = (uint8_t)(((uint8_t)(_r) >> 7) & 1); g_cpu.flag_Z = (uint8_t)((uint8_t)(_r) == 0); } /* $B9AE LSR */
    { uint8_t _a = (uint8_t)((uint8_t)(g_cpu.C & 0xFF)); uint8_t _v = (uint8_t)(0x80); _a = (uint8_t)(_a | _v); g_cpu.C = (uint16_t)((g_cpu.C & 0xFF00) | ((_a) & 0xFF)); g_cpu.flag_N = (uint8_t)(((uint8_t)(_a) >> 7) & 1); g_cpu.flag_Z = (uint8_t)((uint8_t)(_a) == 0); } /* $B9AF ORA */
    bus_write8(0x00, (uint16_t)(g_cpu.DP + 0x2C + g_cpu.X), (uint8_t)((uint8_t)(g_cpu.C & 0xFF))); /* $B9B1 STA */
    { uint8_t _a = (uint8_t)((uint8_t)(g_cpu.C & 0xFF)); uint8_t _v = (uint8_t)(0x10); _a = (uint8_t)(_a | _v); g_cpu.C = (uint16_t)((g_cpu.C & 0xFF00) | ((_a) & 0xFF)); g_cpu.flag_N = (uint8_t)(((uint8_t)(_a) >> 7) & 1); g_cpu.flag_Z = (uint8_t)((uint8_t)(_a) == 0); } /* $B9B3 ORA */
    bus_write8(0x00, (uint16_t)(g_cpu.DP + 0x6C + g_cpu.X), (uint8_t)((uint8_t)(g_cpu.C & 0xFF))); /* $B9B5 STA */
    { uint16_t _t = (uint16_t)((g_cpu.X) + 1); g_cpu.X = (uint16_t)((_t) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_t) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_t) == 0); } /* $B9B7 INX */
    { uint16_t _t = (uint16_t)((g_cpu.X) + 1); g_cpu.X = (uint16_t)((_t) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_t) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_t) == 0); } /* $B9B8 INX */
    { uint8_t _v = (uint8_t)(bus_read8(g_cpu.DB, (uint16_t)(0x0000 + g_cpu.Y))); g_cpu.C = (uint16_t)((g_cpu.C & 0xFF00) | ((_v) & 0xFF)); g_cpu.flag_N = (uint8_t)(((uint8_t)(_v) >> 7) & 1); g_cpu.flag_Z = (uint8_t)((uint8_t)(_v) == 0); } /* $B9B9 LDA */
    { uint8_t _a = (uint8_t)((uint8_t)(g_cpu.C & 0xFF)); uint8_t _v = (uint8_t)(0x0F); _a = (uint8_t)(_a & _v); g_cpu.C = (uint16_t)((g_cpu.C & 0xFF00) | ((_a) & 0xFF)); g_cpu.flag_N = (uint8_t)(((uint8_t)(_a) >> 7) & 1); g_cpu.flag_Z = (uint8_t)((uint8_t)(_a) == 0); } /* $B9BC AND */
    { uint8_t _a = (uint8_t)((uint8_t)(g_cpu.C & 0xFF)); uint8_t _v = (uint8_t)(0x80); _a = (uint8_t)(_a | _v); g_cpu.C = (uint16_t)((g_cpu.C & 0xFF00) | ((_a) & 0xFF)); g_cpu.flag_N = (uint8_t)(((uint8_t)(_a) >> 7) & 1); g_cpu.flag_Z = (uint8_t)((uint8_t)(_a) == 0); } /* $B9BE ORA */
    bus_write8(0x00, (uint16_t)(g_cpu.DP + 0x2C + g_cpu.X), (uint8_t)((uint8_t)(g_cpu.C & 0xFF))); /* $B9C0 STA */
    { uint8_t _a = (uint8_t)((uint8_t)(g_cpu.C & 0xFF)); uint8_t _v = (uint8_t)(0x10); _a = (uint8_t)(_a | _v); g_cpu.C = (uint16_t)((g_cpu.C & 0xFF00) | ((_a) & 0xFF)); g_cpu.flag_N = (uint8_t)(((uint8_t)(_a) >> 7) & 1); g_cpu.flag_Z = (uint8_t)((uint8_t)(_a) == 0); } /* $B9C2 ORA */
    bus_write8(0x00, (uint16_t)(g_cpu.DP + 0x6C + g_cpu.X), (uint8_t)((uint8_t)(g_cpu.C & 0xFF))); /* $B9C4 STA */
    { uint16_t _t = (uint16_t)((g_cpu.X) + 1); g_cpu.X = (uint16_t)((_t) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_t) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_t) == 0); } /* $B9C6 INX */
    { uint16_t _t = (uint16_t)((g_cpu.X) + 1); g_cpu.X = (uint16_t)((_t) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_t) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_t) == 0); } /* $B9C7 INX */
    { uint16_t _t = (uint16_t)((g_cpu.X) + 1); g_cpu.X = (uint16_t)((_t) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_t) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_t) == 0); } /* $B9C8 INX */
    { uint16_t _t = (uint16_t)((g_cpu.X) + 1); g_cpu.X = (uint16_t)((_t) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_t) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_t) == 0); } /* $B9C9 INX */
    return;            /* $B9CA RTS */
}

/* Auto-generated by tools/recomp/autogen.py from $80:8BBF
 * entry M=1 X=1 (P=$30). Validate with the diff harness. */
RECOMP_PATCH(smk_808BBF, 0x808BBF) {
    { uint8_t _v = (uint8_t)(bus_read8(g_cpu.DB, (uint16_t)(0x016A + g_cpu.X))); g_cpu.C = (uint16_t)((g_cpu.C & 0xFF00) | ((_v) & 0xFF)); g_cpu.flag_N = (uint8_t)(((uint8_t)(_v) >> 7) & 1); g_cpu.flag_Z = (uint8_t)((uint8_t)(_v) == 0); } /* $8BBF LDA */
    bus_write8(g_cpu.DB, 0x2131, (uint8_t)((uint8_t)(g_cpu.C & 0xFF))); /* $8BC2 STA */
    { uint8_t _v = (uint8_t)(bus_read8(g_cpu.DB, (uint16_t)(0x016C + g_cpu.X))); g_cpu.C = (uint16_t)((g_cpu.C & 0xFF00) | ((_v) & 0xFF)); g_cpu.flag_N = (uint8_t)(((uint8_t)(_v) >> 7) & 1); g_cpu.flag_Z = (uint8_t)((uint8_t)(_v) == 0); } /* $8BC5 LDA */
    bus_write8(g_cpu.DB, 0x2132, (uint8_t)((uint8_t)(g_cpu.C & 0xFF))); /* $8BC8 STA */
    { uint8_t _v = (uint8_t)(bus_read8(g_cpu.DB, (uint16_t)(0x016E + g_cpu.X))); g_cpu.C = (uint16_t)((g_cpu.C & 0xFF00) | ((_v) & 0xFF)); g_cpu.flag_N = (uint8_t)(((uint8_t)(_v) >> 7) & 1); g_cpu.flag_Z = (uint8_t)((uint8_t)(_v) == 0); } /* $8BCB LDA */
    bus_write8(g_cpu.DB, 0x2132, (uint8_t)((uint8_t)(g_cpu.C & 0xFF))); /* $8BCE STA */
    { uint8_t _v = (uint8_t)(bus_read8(g_cpu.DB, (uint16_t)(0x0170 + g_cpu.X))); g_cpu.C = (uint16_t)((g_cpu.C & 0xFF00) | ((_v) & 0xFF)); g_cpu.flag_N = (uint8_t)(((uint8_t)(_v) >> 7) & 1); g_cpu.flag_Z = (uint8_t)((uint8_t)(_v) == 0); } /* $8BD1 LDA */
    bus_write8(g_cpu.DB, 0x2132, (uint8_t)((uint8_t)(g_cpu.C & 0xFF))); /* $8BD4 STA */
    { uint8_t _v = (uint8_t)(bus_read8(g_cpu.DB, (uint16_t)(0x0108 + g_cpu.X))); g_cpu.C = (uint16_t)((g_cpu.C & 0xFF00) | ((_v) & 0xFF)); g_cpu.flag_N = (uint8_t)(((uint8_t)(_v) >> 7) & 1); g_cpu.flag_Z = (uint8_t)((uint8_t)(_v) == 0); } /* $8BD7 LDA */
    bus_write8(g_cpu.DB, 0x2125, (uint8_t)((uint8_t)(g_cpu.C & 0xFF))); /* $8BDA STA */
    { uint8_t _v = (uint8_t)(bus_read8(g_cpu.DB, (uint16_t)(0x014E + g_cpu.X))); g_cpu.C = (uint16_t)((g_cpu.C & 0xFF00) | ((_v) & 0xFF)); g_cpu.flag_N = (uint8_t)(((uint8_t)(_v) >> 7) & 1); g_cpu.flag_Z = (uint8_t)((uint8_t)(_v) == 0); } /* $8BDD LDA */
    bus_write8(g_cpu.DB, 0x212E, (uint8_t)((uint8_t)(g_cpu.C & 0xFF))); /* $8BE0 STA */
    { uint8_t _v = (uint8_t)(bus_read8(g_cpu.DB, (uint16_t)(0x017A + g_cpu.X))); g_cpu.C = (uint16_t)((g_cpu.C & 0xFF00) | ((_v) & 0xFF)); g_cpu.flag_N = (uint8_t)(((uint8_t)(_v) >> 7) & 1); g_cpu.flag_Z = (uint8_t)((uint8_t)(_v) == 0); } /* $8BE3 LDA */
    bus_write8(g_cpu.DB, 0x2130, (uint8_t)((uint8_t)(g_cpu.C & 0xFF))); /* $8BE6 STA */
    return;            /* $8BE9 RTS */
}

/* Auto-generated by tools/recomp/autogen.py from $80:86A0
 * entry M=0 X=0 (P=$00). Validate with the diff harness. */
RECOMP_PATCH(smk_8086A0, 0x8086A0) {
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0xA4 + g_cpu.X))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $86A0 LDA */
    { uint16_t _a = (uint16_t)(g_cpu.C); uint16_t _v = (uint16_t)(0x0002); uint16_t _t = (uint16_t)(_a - _v); g_cpu.flag_C = (uint8_t)(_a >= _v); g_cpu.flag_Z = (uint8_t)(_a == _v); g_cpu.flag_N = (uint8_t)((_t >> 15) & 1); } /* $86A2 CMP */
    if (g_cpu.flag_Z) goto L_86AB;  /* $86A5 BEQ */
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0xAC + g_cpu.X))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $86A7 LDA */
    if (!g_cpu.flag_N) goto L_86CB;  /* $86A9 BPL */
  L_86AB:;
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x0016 + g_cpu.Y))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $86AB LDA */
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x00), (uint16_t)(g_cpu.C)); /* $86AE STA */
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x0018 + g_cpu.Y))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $86B0 LDA */
    { uint8_t _bk = (uint8_t)(0x00); uint16_t _ad = (uint16_t)((uint16_t)(g_cpu.DP + 0x00)); uint16_t _x = bus_read16(_bk, _ad); uint8_t _c = (uint8_t)((_x >> 15) & 1); uint16_t _r = (uint16_t)((_x << 1) | (g_cpu.flag_C ? 1 : 0)); bus_write16(_bk, _ad, _r); g_cpu.flag_C = _c; g_cpu.flag_N = (uint8_t)(((uint16_t)(_r) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_r) == 0); } /* $86B3 ROL */
    { uint16_t _x = (uint16_t)(g_cpu.C); uint8_t _c = (uint8_t)((_x >> 15) & 1); uint16_t _r = (uint16_t)((_x << 1) | (g_cpu.flag_C ? 1 : 0)); g_cpu.flag_C = _c; g_cpu.C = (uint16_t)((_r) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_r) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_r) == 0); } /* $86B5 ROL */
    { uint8_t _bk = (uint8_t)(0x00); uint16_t _ad = (uint16_t)((uint16_t)(g_cpu.DP + 0x00)); uint16_t _x = bus_read16(_bk, _ad); uint8_t _c = (uint8_t)((_x >> 15) & 1); uint16_t _r = (uint16_t)((_x << 1) | (g_cpu.flag_C ? 1 : 0)); bus_write16(_bk, _ad, _r); g_cpu.flag_C = _c; g_cpu.flag_N = (uint8_t)(((uint16_t)(_r) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_r) == 0); } /* $86B6 ROL */
    { uint16_t _x = (uint16_t)(g_cpu.C); uint8_t _c = (uint8_t)((_x >> 15) & 1); uint16_t _r = (uint16_t)((_x << 1) | (g_cpu.flag_C ? 1 : 0)); g_cpu.flag_C = _c; g_cpu.C = (uint16_t)((_r) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_r) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_r) == 0); } /* $86B8 ROL */
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x88 + g_cpu.X), (uint16_t)(g_cpu.C)); /* $86B9 STA */
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x001A + g_cpu.Y))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $86BB LDA */
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x00), (uint16_t)(g_cpu.C)); /* $86BE STA */
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x001C + g_cpu.Y))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $86C0 LDA */
    { uint8_t _bk = (uint8_t)(0x00); uint16_t _ad = (uint16_t)((uint16_t)(g_cpu.DP + 0x00)); uint16_t _x = bus_read16(_bk, _ad); uint8_t _c = (uint8_t)((_x >> 15) & 1); uint16_t _r = (uint16_t)((_x << 1) | (g_cpu.flag_C ? 1 : 0)); bus_write16(_bk, _ad, _r); g_cpu.flag_C = _c; g_cpu.flag_N = (uint8_t)(((uint16_t)(_r) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_r) == 0); } /* $86C3 ROL */
    { uint16_t _x = (uint16_t)(g_cpu.C); uint8_t _c = (uint8_t)((_x >> 15) & 1); uint16_t _r = (uint16_t)((_x << 1) | (g_cpu.flag_C ? 1 : 0)); g_cpu.flag_C = _c; g_cpu.C = (uint16_t)((_r) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_r) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_r) == 0); } /* $86C5 ROL */
    { uint8_t _bk = (uint8_t)(0x00); uint16_t _ad = (uint16_t)((uint16_t)(g_cpu.DP + 0x00)); uint16_t _x = bus_read16(_bk, _ad); uint8_t _c = (uint8_t)((_x >> 15) & 1); uint16_t _r = (uint16_t)((_x << 1) | (g_cpu.flag_C ? 1 : 0)); bus_write16(_bk, _ad, _r); g_cpu.flag_C = _c; g_cpu.flag_N = (uint8_t)(((uint16_t)(_r) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_r) == 0); } /* $86C6 ROL */
    { uint16_t _x = (uint16_t)(g_cpu.C); uint8_t _c = (uint8_t)((_x >> 15) & 1); uint16_t _r = (uint16_t)((_x << 1) | (g_cpu.flag_C ? 1 : 0)); g_cpu.flag_C = _c; g_cpu.C = (uint16_t)((_r) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_r) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_r) == 0); } /* $86C8 ROL */
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x8C + g_cpu.X), (uint16_t)(g_cpu.C)); /* $86C9 STA */
  L_86CB:;
    return;            /* $86CB RTS */
}

/* Auto-generated by tools/recomp/autogen.py from $80:BBCC
 * entry M=0 X=0 (P=$00). Validate with the diff harness. */
RECOMP_PATCH(smk_80BBCC, 0x80BBCC) {
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0xB8))); g_cpu.X = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $BBCC LDX */
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x1E96 + g_cpu.X))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $BBCE LDA */
    if (!g_cpu.flag_N) goto L_BBFE;  /* $BBD1 BPL */
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x1EB0 + g_cpu.X))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $BBD3 LDA */
    if (g_cpu.flag_N) goto L_BBE2;  /* $BBD6 BMI */
    { uint16_t _a = (uint16_t)(g_cpu.C); uint16_t _v = (uint16_t)(0x8000); _a = (uint16_t)(_a | _v); g_cpu.C = (uint16_t)((_a) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_a) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_a) == 0); } /* $BBD8 ORA */
    bus_write16(g_cpu.DB, (uint16_t)(0x1EB0 + g_cpu.X), (uint16_t)(g_cpu.C)); /* $BBDB STA */
    func_table_call(0x81AF50);                     /* $BBDE JSL $81AF50 */
  L_BBE2:;
    { uint16_t _v = (uint16_t)(0x0020); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $BBE2 LDA */
    bus_write16(g_cpu.DB, (uint16_t)(0x1EF8 + g_cpu.X), (uint16_t)(g_cpu.C)); /* $BBE5 STA */
    func_table_call(0x81BB4A);                     /* $BBE8 JSL $81BB4A */
    { uint16_t _v = (uint16_t)(0xD3A1); g_cpu.X = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $BBEC LDX */
    func_table_call(0x81CC26);                     /* $BBEF JSL $81CC26 */
    { uint16_t _v = (uint16_t)(0xD3B0); g_cpu.X = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $BBF3 LDX */
    func_table_call(0x81CC26);                     /* $BBF6 JSL $81CC26 */
    func_table_call(0x81AFB4);                     /* $BBFA JSL $81AFB4 */
  L_BBFE:;
    return;            /* $BBFE RTS */
}

/* Auto-generated by tools/recomp/autogen.py from $80:BA50
 * entry M=0 X=0 (P=$00). Validate with the diff harness. */
RECOMP_PATCH(smk_80BA50, 0x80BA50) {
    { g_cpu.S--; bus_wram_write16(g_cpu.S, 0x8085); g_cpu.S--; } /* $BA50 PEA */
    op_plb();                                      /* $BA53 PLB */
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0xB8))); g_cpu.X = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $BA54 LDX */
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0xC8 + g_cpu.X))); g_cpu.Y = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $BA56 LDY */
    if (g_cpu.flag_N) goto L_BA5E;  /* $BA58 BMI */
    func_table_call(0x85DFB4);                     /* $BA5A JSL $85DFB4 */
  L_BA5E:;
    op_plb();                                      /* $BA5E PLB */
    return;            /* $BA5F RTS */
}

/* Auto-generated by tools/recomp/autogen.py from $80:8D83
 * entry M=0 X=0 (P=$00). Validate with the diff harness. */
RECOMP_PATCH(smk_808D83, 0x808D83) {
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0x2C))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8D83 LDA */
    if (!g_cpu.flag_Z) goto L_8DD0;  /* $8D85 BNE */
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, 0x012E)); g_cpu.X = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8D87 LDX */
    { uint16_t _a = (uint16_t)(g_cpu.X); uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, 0x0144)); uint16_t _t = (uint16_t)(_a - _v); g_cpu.flag_C = (uint8_t)(_a >= _v); g_cpu.flag_Z = (uint8_t)(_a == _v); g_cpu.flag_N = (uint8_t)((_t >> 15) & 1); } /* $8D8A CPX */
    if (g_cpu.flag_C) goto L_8DD0;  /* $8D8D BCS */
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0x4A))); g_cpu.Y = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8D8F LDY */
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x8DD1 + g_cpu.X))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8D91 LDA */
    bus_write16(g_cpu.DB, (uint16_t)(0x0EA0 + g_cpu.Y), (uint16_t)(g_cpu.C)); /* $8D94 STA */
    g_cpu.flag_C = 0;                              /* $8D97 CLC */
    op_adc_imm16(0x0100);                          /* $8D98 ADC */
    bus_write16(g_cpu.DB, (uint16_t)(0x0EA6 + g_cpu.Y), (uint16_t)(g_cpu.C)); /* $8D9B STA */
    { uint16_t _v = (uint16_t)(0x407F); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8D9E LDA */
    bus_write16(g_cpu.DB, (uint16_t)(0x0EA4 + g_cpu.Y), (uint16_t)(g_cpu.C)); /* $8DA1 STA */
    bus_write16(g_cpu.DB, (uint16_t)(0x0EAA + g_cpu.Y), (uint16_t)(g_cpu.C)); /* $8DA4 STA */
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x0130 + g_cpu.X))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8DA7 LDA */
    { uint16_t _a = (uint16_t)(g_cpu.X); uint16_t _v = (uint16_t)(0x0008); uint16_t _t = (uint16_t)(_a - _v); g_cpu.flag_C = (uint8_t)(_a >= _v); g_cpu.flag_Z = (uint8_t)(_a == _v); g_cpu.flag_N = (uint8_t)((_t >> 15) & 1); } /* $8DAA CPX */
    if (g_cpu.flag_C) goto L_8DB5;  /* $8DAD BCS */
    op_tax();                                      /* $8DAF TAX */
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x8DE1 + g_cpu.X))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8DB0 LDA */
    goto L_8DB9;   /* $8DB3 BRA */
  L_8DB5:;
    op_tax();                                      /* $8DB5 TAX */
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x8DF1 + g_cpu.X))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8DB6 LDA */
  L_8DB9:;
    bus_write16(g_cpu.DB, (uint16_t)(0x0EA2 + g_cpu.Y), (uint16_t)(g_cpu.C)); /* $8DB9 STA */
    g_cpu.flag_C = 0;                              /* $8DBC CLC */
    op_adc_imm16(0x0200);                          /* $8DBD ADC */
    bus_write16(g_cpu.DB, (uint16_t)(0x0EA8 + g_cpu.Y), (uint16_t)(g_cpu.C)); /* $8DC0 STA */
    op_tya();                                      /* $8DC3 TYA */
    g_cpu.flag_C = 0;                              /* $8DC4 CLC */
    op_adc_imm16(0x000C);                          /* $8DC5 ADC */
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x4A), (uint16_t)(g_cpu.C)); /* $8DC8 STA */
    { uint8_t _bk = (uint8_t)(g_cpu.DB); uint16_t _ad = (uint16_t)(0x012E); uint16_t _t = (uint16_t)(bus_read16(_bk, _ad) + 1); bus_write16(_bk, _ad, _t); g_cpu.flag_N = (uint8_t)(((uint16_t)(_t) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_t) == 0); } /* $8DCA INC */
    { uint8_t _bk = (uint8_t)(g_cpu.DB); uint16_t _ad = (uint16_t)(0x012E); uint16_t _t = (uint16_t)(bus_read16(_bk, _ad) + 1); bus_write16(_bk, _ad, _t); g_cpu.flag_N = (uint8_t)(((uint16_t)(_t) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_t) == 0); } /* $8DCD INC */
  L_8DD0:;
    return;            /* $8DD0 RTS */
}

/* Auto-generated by tools/recomp/autogen.py from $80:B7EB
 * entry M=0 X=0 (P=$00). Validate with the diff harness. */
RECOMP_PATCH(smk_80B7EB, 0x80B7EB) {
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0xC6 + g_cpu.X))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $B7EB LDA */
    if (g_cpu.flag_Z) goto L_B80F;  /* $B7ED BEQ */
    if (g_cpu.flag_N) goto L_B7F7;  /* $B7EF BMI */
    { uint16_t _t = (uint16_t)((g_cpu.C) - 1); g_cpu.C = (uint16_t)((_t) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_t) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_t) == 0); } /* $B7F1 DEC */
    if (g_cpu.flag_Z) goto L_B804;  /* $B7F2 BEQ */
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0xC6 + g_cpu.X), (uint16_t)(g_cpu.C)); /* $B7F4 STA */
    return;            /* $B7F6 RTS */
  L_B7F7:;
    { uint16_t _t = (uint16_t)((g_cpu.C) + 1); g_cpu.C = (uint16_t)((_t) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_t) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_t) == 0); } /* $B7F7 INC */
    if (g_cpu.flag_Z) goto L_B7FD;  /* $B7F8 BEQ */
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0xC6 + g_cpu.X), (uint16_t)(g_cpu.C)); /* $B7FA STA */
    return;            /* $B7FC RTS */
  L_B7FD:;
    func_table_call_jsr(0x80B847);                 /* $B7FD JSR $80B847 */
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0xC6 + g_cpu.X), (uint16_t)(g_cpu.C)); /* $B800 STA */
    goto L_B826;   /* $B802 BRA */
  L_B804:;
    func_table_call_jsr(0x80B847);                 /* $B804 JSR $80B847 */
    { uint16_t _a = (uint16_t)(g_cpu.C); uint16_t _v = (uint16_t)(0xFFFF); _a = (uint16_t)(_a ^ _v); g_cpu.C = (uint16_t)((_a) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_a) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_a) == 0); } /* $B807 EOR */
    { uint16_t _t = (uint16_t)((g_cpu.C) + 1); g_cpu.C = (uint16_t)((_t) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_t) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_t) == 0); } /* $B80A INC */
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0xC6 + g_cpu.X), (uint16_t)(g_cpu.C)); /* $B80B STA */
    goto L_B815;   /* $B80D BRA */
  L_B80F:;
    func_table_call_jsr(0x80B847);                 /* $B80F JSR $80B847 */
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0xC6 + g_cpu.X), (uint16_t)(g_cpu.C)); /* $B812 STA */
    return;            /* $B814 RTS */
  L_B815:;
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0x12 + g_cpu.X))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $B815 LDA */
    op_tay();                                      /* $B817 TAY */
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0xB837 + g_cpu.Y))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $B818 LDA */
    op_phx16();                                    /* $B81B PHX */
    op_tax();                                      /* $B81C TAX */
    { uint16_t _v = (uint16_t)(0x35A9); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $B81D LDA */
    bus_write16(0x7E, (uint16_t)(0x3A80 + g_cpu.X), (uint16_t)(g_cpu.C)); /* $B820 STA */
    op_plx16();                                    /* $B824 PLX */
    return;            /* $B825 RTS */
  L_B826:;
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0x12 + g_cpu.X))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $B826 LDA */
    op_tay();                                      /* $B828 TAY */
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0xB837 + g_cpu.Y))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $B829 LDA */
    op_phx16();                                    /* $B82C PHX */
    op_tax();                                      /* $B82D TAX */
    { uint16_t _v = (uint16_t)(0x2525); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $B82E LDA */
    bus_write16(0x7E, (uint16_t)(0x3A80 + g_cpu.X), (uint16_t)(g_cpu.C)); /* $B831 STA */
    op_plx16();                                    /* $B835 PLX */
    return;            /* $B836 RTS */
}

/* Auto-generated by tools/recomp/autogen.py from $80:9EB2
 * entry M=0 X=0 (P=$00). Validate with the diff harness. */
RECOMP_PATCH(smk_809EB2, 0x809EB2) {
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, 0x0E68)); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $9EB2 LDA */
    if (g_cpu.flag_Z) goto L_9EC7;  /* $9EB5 BEQ */
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0x32))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $9EB7 LDA */
    if (!g_cpu.flag_Z) goto L_9EC7;  /* $9EB9 BNE */
    { uint16_t _v = (uint16_t)(0x0000); g_cpu.X = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $9EBB LDX */
    func_table_call_jsr(0x809FAC);                 /* $9EBE JSR $809FAC */
    { uint16_t _v = (uint16_t)(0x0002); g_cpu.X = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $9EC1 LDX */
    func_table_call_jsr(0x809FAC);                 /* $9EC4 JSR $809FAC */
  L_9EC7:;
    return;            /* $9EC7 RTS */
}

/* Auto-generated by tools/recomp/autogen.py from $85:84D1
 * entry M=1 X=1 (P=$30). Validate with the diff harness. */
RECOMP_PATCH(smk_8584D1, 0x8584D1) {
    op_rep(0x20);                                  /* $84D1 REP */
    op_inc_dp16(0x64);                             /* $84D3 INC */
    op_sep(0x20);                                  /* $84D5 SEP */
    return;            /* $84D7 RTS */
}

/* Auto-generated by tools/recomp/autogen.py from $85:8EE9
 * entry M=0 X=0 (P=$00). Validate with the diff harness. */
RECOMP_PATCH(smk_858EE9, 0x858EE9) {
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0x75))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8EE9 LDA */
    op_tax();                                      /* $8EEB TAX */
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x8FE9 + g_cpu.X))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8EEC LDA */
    op_tax();                                      /* $8EEF TAX */
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0x1C + g_cpu.X))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8EF0 LDA */
    { uint16_t _a = (uint16_t)(g_cpu.C); uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0x44 + g_cpu.X))); uint16_t _t = (uint16_t)(_a - _v); g_cpu.flag_C = (uint8_t)(_a >= _v); g_cpu.flag_Z = (uint8_t)(_a == _v); g_cpu.flag_N = (uint8_t)((_t >> 15) & 1); } /* $8EF2 CMP */
    if (!g_cpu.flag_Z) goto L_8EFA;  /* $8EF4 BNE */
    { uint16_t _t = (uint16_t)((g_cpu.C) + 1); g_cpu.C = (uint16_t)((_t) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_t) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_t) == 0); } /* $8EF6 INC */
    func_table_call_jsr(0x858EFB); return;  /* $8EF7 JMP (tail) $858EFB */
  L_8EFA:;
    { uint16_t _t = (uint16_t)((g_cpu.C) - 1); g_cpu.C = (uint16_t)((_t) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_t) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_t) == 0); } /* $8EFA DEC */
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x1C + g_cpu.X), (uint16_t)(g_cpu.C)); /* $8EFB STA */
    op_inc_dp16(0x75);                             /* $8EFD INC */
    op_inc_dp16(0x75);                             /* $8EFF INC */
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0x75))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8F01 LDA */
    { uint16_t _a = (uint16_t)(g_cpu.C); uint16_t _v = (uint16_t)(0x0010); uint16_t _t = (uint16_t)(_a - _v); g_cpu.flag_C = (uint8_t)(_a >= _v); g_cpu.flag_Z = (uint8_t)(_a == _v); g_cpu.flag_N = (uint8_t)((_t >> 15) & 1); } /* $8F03 CMP */
    if (!g_cpu.flag_Z) goto L_8F0A;  /* $8F06 BNE */
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x75), (uint16_t)(0)); /* $8F08 STZ */
  L_8F0A:;
    return;            /* $8F0A RTS */
}

/* Auto-generated by tools/recomp/autogen.py from $85:B945
 * entry M=0 X=0 (P=$00). Validate with the diff harness. */
RECOMP_PATCH(smk_85B945, 0x85B945) {
    { uint16_t _t = (uint16_t)((g_cpu.Y) + 1); g_cpu.Y = (uint16_t)((_t) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_t) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_t) == 0); } /* $B945 INY */
    { uint16_t _t = (uint16_t)((g_cpu.Y) + 1); g_cpu.Y = (uint16_t)((_t) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_t) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_t) == 0); } /* $B946 INY */
    { uint16_t _t = (uint16_t)((g_cpu.Y) + 1); g_cpu.Y = (uint16_t)((_t) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_t) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_t) == 0); } /* $B947 INY */
    { uint16_t _t = (uint16_t)((g_cpu.Y) + 1); g_cpu.Y = (uint16_t)((_t) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_t) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_t) == 0); } /* $B948 INY */
    return;            /* $B949 RTS */
}

/* Auto-generated by tools/recomp/autogen.py from $85:8FB8
 * entry M=0 X=0 (P=$00). Validate with the diff harness. */
RECOMP_PATCH(smk_858FB8, 0x858FB8) {
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x8FF9 + g_cpu.Y))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8FB8 LDA */
    op_tay();                                      /* $8FBB TAY */
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x22 + g_cpu.X), (uint16_t)(0)); /* $8FBC STZ */
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x0000 + g_cpu.Y))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8FBE LDA */
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x18 + g_cpu.X), (uint16_t)(g_cpu.C)); /* $8FC1 STA */
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x0002 + g_cpu.Y))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8FC3 LDA */
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x1C + g_cpu.X), (uint16_t)(g_cpu.C)); /* $8FC6 STA */
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x0004 + g_cpu.Y))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8FC8 LDA */
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x2A + g_cpu.X), (uint16_t)(g_cpu.C)); /* $8FCB STA */
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x0006 + g_cpu.Y))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8FCD LDA */
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x92 + g_cpu.X), (uint16_t)(g_cpu.C)); /* $8FD0 STA */
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x0008 + g_cpu.Y))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8FD2 LDA */
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x44 + g_cpu.X), (uint16_t)(g_cpu.C)); /* $8FD5 STA */
    return;            /* $8FD7 RTS */
}

