/*
 * smk_autogen.c — functions produced by tools/recomp/autogen.py directly from
 * the ROM bytes + trace-exact entry M/X flags (from SMK_RECOMP_PROFILE). Each is
 * gated byte-identical to the emulation oracle via tools/diff_snapshots.py.
 *
 * Regenerate via: py tools/recomp/autogen.py "<rom>.sfc" <bank:addr> <P> <name>
 * Batch:          py tools/recomp/batch.py "<rom>.sfc" <prof.txt> <out.c>
 */
#include "smk/functions.h"
#include <snesrecomp/snesrecomp.h>
#include <stdint.h>

/* Auto-generated by tools/recomp/autogen.py from $85:84D1
 * entry M=0 X=0 (P=$C2). Validate with the diff harness. */
RECOMP_PATCH(smk_8584D1, 0x8584D1) {
    op_rep(0x20);                                  /* $84D1 REP */
    op_inc_dp16(0x64);                             /* $84D3 INC */
    op_sep(0x20);                                  /* $84D5 SEP */
    return;            /* $84D7 RTS */
}

/* Auto-generated by tools/recomp/autogen.py from $85:8FB8
 * entry M=0 X=0 (P=$00). Validate with the diff harness. */
RECOMP_PATCH(smk_858FB8, 0x858FB8) {
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x8FF9 + g_cpu.Y))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8FB8 LDA */
    op_tay();                                      /* $8FBB TAY */
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x22 + g_cpu.X), (uint16_t)(0)); /* $8FBC STZ */
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x0000 + g_cpu.Y))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8FBE LDA */
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x18 + g_cpu.X), (uint16_t)(g_cpu.C)); /* $8FC1 STA */
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x0002 + g_cpu.Y))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8FC3 LDA */
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x1C + g_cpu.X), (uint16_t)(g_cpu.C)); /* $8FC6 STA */
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x0004 + g_cpu.Y))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8FC8 LDA */
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x2A + g_cpu.X), (uint16_t)(g_cpu.C)); /* $8FCB STA */
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x0006 + g_cpu.Y))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8FCD LDA */
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x92 + g_cpu.X), (uint16_t)(g_cpu.C)); /* $8FD0 STA */
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x0008 + g_cpu.Y))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8FD2 LDA */
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x44 + g_cpu.X), (uint16_t)(g_cpu.C)); /* $8FD5 STA */
    return;            /* $8FD7 RTS */
}

/* Auto-generated by tools/recomp/autogen.py from $81:81C4
 * entry M=0 X=0 (P=$80). Validate with the diff harness. */
RECOMP_PATCH(smk_8181C4, 0x8181C4) {
    { uint16_t _v = (uint16_t)(0x81A8); g_cpu.Y = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $81C4 LDY */
    goto L_81CC;   /* $81C7 BRA */
  L_81CC:;
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x0000 + g_cpu.Y))); g_cpu.X = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $81CC LDX */
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0xB8), (uint16_t)(g_cpu.X)); /* $81CF STX */
    bus_write16(g_cpu.DB, (uint16_t)(0x1EF8 + g_cpu.X), (uint16_t)(0)); /* $81D1 STZ */
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0xC8 + g_cpu.X))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $81D4 LDA */
    bus_write16(g_cpu.DB, 0x0FE0, (uint16_t)(g_cpu.C)); /* $81D6 STA */
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x0002 + g_cpu.Y))); g_cpu.X = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $81D9 LDX */
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0xCE), (uint16_t)(g_cpu.X)); /* $81DC STX */
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x0004 + g_cpu.Y))); g_cpu.X = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $81DE LDX */
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0xCC), (uint16_t)(g_cpu.X)); /* $81E1 STX */
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x0006 + g_cpu.Y))); g_cpu.X = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $81E3 LDX */
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0xBA), (uint16_t)(g_cpu.X)); /* $81E6 STX */
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x0008 + g_cpu.Y))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $81E8 LDA */
    bus_write16(g_cpu.DB, 0x0FE2, (uint16_t)(g_cpu.C)); /* $81EB STA */
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x000A + g_cpu.Y))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $81EE LDA */
    bus_write16(g_cpu.DB, 0x0FE4, (uint16_t)(g_cpu.C)); /* $81F1 STA */
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x000C + g_cpu.Y))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $81F4 LDA */
    bus_write16(g_cpu.DB, 0x0FDC, (uint16_t)(g_cpu.C)); /* $81F7 STA */
    return;            /* $81FA RTS */
}

/* Auto-generated by tools/recomp/autogen.py from $80:C279
 * entry M=0 X=0 (P=$00). Validate with the diff harness. */
RECOMP_PATCH(smk_80C279, 0x80C279) {
    op_phy16();                                    /* $C279 PHY */
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x0002 + g_cpu.Y))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $C27A LDA */
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x02 + g_cpu.Y), (uint16_t)(g_cpu.X)); /* $C27D STX */
    op_tay();                                      /* $C27F TAY */
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x0000 + g_cpu.Y))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $C280 LDA */
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x00 + g_cpu.Y), (uint16_t)(g_cpu.X)); /* $C283 STX */
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x00 + g_cpu.X), (uint16_t)(g_cpu.C)); /* $C285 STA */
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x02 + g_cpu.X), (uint16_t)(g_cpu.Y)); /* $C287 STY */
    op_ply16();                                    /* $C289 PLY */
    return;            /* $C28A RTS */
}

/* Auto-generated by tools/recomp/autogen.py from $81:9587
 * entry M=0 X=0 (P=$00). Validate with the diff harness. */
RECOMP_PATCH(smk_819587, 0x819587) {
    op_phy16();                                    /* $9587 PHY */
    op_sep(0x20);                                  /* $9588 SEP */
    { uint8_t _v = (uint8_t)(bus_read8(g_cpu.DB, (uint16_t)(0x0000 + g_cpu.X))); g_cpu.C = (uint16_t)((g_cpu.C & 0xFF00) | ((_v) & 0xFF)); g_cpu.flag_N = (uint8_t)(((uint8_t)(_v) >> 7) & 1); g_cpu.flag_Z = (uint8_t)((uint8_t)(_v) == 0); } /* $958A LDA */
    bus_write8(g_cpu.DB, 0x211B, (uint8_t)((uint8_t)(g_cpu.C & 0xFF))); /* $958D STA */
    { uint8_t _v = (uint8_t)(bus_read8(g_cpu.DB, (uint16_t)(0x0001 + g_cpu.X))); g_cpu.C = (uint16_t)((g_cpu.C & 0xFF00) | ((_v) & 0xFF)); g_cpu.flag_N = (uint8_t)(((uint8_t)(_v) >> 7) & 1); g_cpu.flag_Z = (uint8_t)((uint8_t)(_v) == 0); } /* $9590 LDA */
    bus_write8(g_cpu.DB, 0x211B, (uint8_t)((uint8_t)(g_cpu.C & 0xFF))); /* $9593 STA */
    { uint8_t _v = (uint8_t)(0x01); g_cpu.C = (uint16_t)((g_cpu.C & 0xFF00) | ((_v) & 0xFF)); g_cpu.flag_N = (uint8_t)(((uint8_t)(_v) >> 7) & 1); g_cpu.flag_Z = (uint8_t)((uint8_t)(_v) == 0); } /* $9596 LDA */
    bus_write8(g_cpu.DB, 0x211C, (uint8_t)((uint8_t)(g_cpu.C & 0xFF))); /* $9598 STA */
    bus_write8(g_cpu.DB, 0x211C, (uint8_t)((uint8_t)(g_cpu.C & 0xFF))); /* $959B STA */
    { uint16_t _v = (uint16_t)(0x3481); g_cpu.Y = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $959E LDY */
    bus_write16(g_cpu.DB, 0x4300, (uint16_t)(g_cpu.Y)); /* $95A1 STY */
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x0002 + g_cpu.X))); g_cpu.Y = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $95A4 LDY */
    bus_write16(g_cpu.DB, 0x4302, (uint16_t)(g_cpu.Y)); /* $95A7 STY */
    { uint8_t _v = (uint8_t)(bus_read8(g_cpu.DB, (uint16_t)(0x0004 + g_cpu.X))); g_cpu.C = (uint16_t)((g_cpu.C & 0xFF00) | ((_v) & 0xFF)); g_cpu.flag_N = (uint8_t)(((uint8_t)(_v) >> 7) & 1); g_cpu.flag_Z = (uint8_t)((uint8_t)(_v) == 0); } /* $95AA LDA */
    bus_write8(g_cpu.DB, 0x4304, (uint8_t)((uint8_t)(g_cpu.C & 0xFF))); /* $95AD STA */
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x0005 + g_cpu.X))); g_cpu.Y = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $95B0 LDY */
    bus_write16(g_cpu.DB, 0x4305, (uint16_t)(g_cpu.Y)); /* $95B3 STY */
    { uint8_t _v = (uint8_t)(0x01); g_cpu.C = (uint16_t)((g_cpu.C & 0xFF00) | ((_v) & 0xFF)); g_cpu.flag_N = (uint8_t)(((uint8_t)(_v) >> 7) & 1); g_cpu.flag_Z = (uint8_t)((uint8_t)(_v) == 0); } /* $95B6 LDA */
    bus_write8(g_cpu.DB, 0x420B, (uint8_t)((uint8_t)(g_cpu.C & 0xFF))); /* $95B8 STA */
    op_rep(0x20);                                  /* $95BB REP */
    op_ply16();                                    /* $95BD PLY */
    return;            /* $95BE RTL */
}

