/*
 * smk_autogen.c — functions produced by tools/recomp/autogen.py + batch.py
 * directly from ROM bytes + trace-exact entry M/X flags (SMK_RECOMP_PROFILE).
 * Each is gated byte-identical to the emulation oracle via diff_snapshots.py.
 *
 * Regenerate: py tools/recomp/batch.py "<rom>.sfc" <prof.txt> src/recomp/smk_autogen.c
 */
#include "smk/functions.h"
#include <snesrecomp/snesrecomp.h>
#include <snesrecomp/func_table.h>
#include <stdint.h>

/* Auto-generated by tools/recomp/autogen.py from $80:9EB2
 * entry M=0 X=0 (P=$00). Validate with the diff harness. */
RECOMP_PATCH(smk_809EB2, 0x809EB2) {
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, 0x0E68)); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $9EB2 LDA */
    if (g_cpu.flag_Z) goto L_9EC7;  /* $9EB5 BEQ */
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0x32))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $9EB7 LDA */
    if (!g_cpu.flag_Z) goto L_9EC7;  /* $9EB9 BNE */
    { uint16_t _v = (uint16_t)(0x0000); g_cpu.X = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $9EBB LDX */
    func_table_call_jsr(0x809FAC);                 /* $9EBE JSR $809FAC */
    { uint16_t _v = (uint16_t)(0x0002); g_cpu.X = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $9EC1 LDX */
    func_table_call_jsr(0x809FAC);                 /* $9EC4 JSR $809FAC */
  L_9EC7:;
    return;            /* $9EC7 RTS */
}

/* Auto-generated by tools/recomp/autogen.py from $85:92F9
 * entry M=0 X=0 (P=$00). Validate with the diff harness. */
RECOMP_PATCH(smk_8592F9, 0x8592F9) {
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0x48))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $92F9 LDA */
    if (!g_cpu.flag_Z) goto L_9331;  /* $92FB BNE */
    op_sep(0x20);                                  /* $92FD SEP */
    { uint8_t _v = (uint8_t)(bus_read8(g_cpu.DB, 0x0161)); g_cpu.C = (uint16_t)((g_cpu.C & 0xFF00) | ((_v) & 0xFF)); g_cpu.flag_N = (uint8_t)(((uint8_t)(_v) >> 7) & 1); g_cpu.flag_Z = (uint8_t)((uint8_t)(_v) == 0); } /* $92FF LDA */
    { uint8_t _a = (uint8_t)((uint8_t)(g_cpu.C & 0xFF)); uint8_t _v = (uint8_t)(0x0F); uint8_t _t = (uint8_t)(_a - _v); g_cpu.flag_C = (uint8_t)(_a >= _v); g_cpu.flag_Z = (uint8_t)(_a == _v); g_cpu.flag_N = (uint8_t)((_t >> 7) & 1); } /* $9302 CMP */
    op_rep(0x20);                                  /* $9304 REP */
    if (!g_cpu.flag_Z) goto L_9331;  /* $9306 BNE */
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0x28))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $9308 LDA */
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x6A), (uint16_t)(g_cpu.C)); /* $930A STA */
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0x2A))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $930C LDA */
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x6C), (uint16_t)(g_cpu.C)); /* $930E STA */
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0x36))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $9310 LDA */
    { uint16_t _a = (uint16_t)(g_cpu.C); uint16_t _v = (uint16_t)(0x0004); uint16_t _t = (uint16_t)(_a - _v); g_cpu.flag_C = (uint8_t)(_a >= _v); g_cpu.flag_Z = (uint8_t)(_a == _v); g_cpu.flag_N = (uint8_t)((_t >> 15) & 1); } /* $9312 CMP */
    if (g_cpu.flag_Z) goto L_931F;  /* $9315 BEQ */
    { uint16_t _a = (uint16_t)(g_cpu.C); uint16_t _v = (uint16_t)(0x0006); uint16_t _t = (uint16_t)(_a - _v); g_cpu.flag_C = (uint8_t)(_a >= _v); g_cpu.flag_Z = (uint8_t)(_a == _v); g_cpu.flag_N = (uint8_t)((_t >> 15) & 1); } /* $9317 CMP */
    if (g_cpu.flag_Z) goto L_9320;  /* $931A BEQ */
  L_931C:;
    func_table_call_jsr(0x859336);                 /* $931C JSR $859336 */
  L_931F:;
    return;            /* $931F RTS */
  L_9320:;
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0x2C))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $9320 LDA */
    { uint16_t _a = (uint16_t)(g_cpu.C); uint16_t _v = (uint16_t)(0x0004); uint16_t _t = (uint16_t)(_a - _v); g_cpu.flag_C = (uint8_t)(_a >= _v); g_cpu.flag_Z = (uint8_t)(_a == _v); g_cpu.flag_N = (uint8_t)((_t >> 15) & 1); } /* $9322 CMP */
    if (!g_cpu.flag_Z) goto L_931C;  /* $9325 BNE */
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0x2E))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $9327 LDA */
    { uint16_t _a = (uint16_t)(g_cpu.C); uint16_t _v = (uint16_t)(0x0002); uint16_t _t = (uint16_t)(_a - _v); g_cpu.flag_C = (uint8_t)(_a >= _v); g_cpu.flag_Z = (uint8_t)(_a == _v); g_cpu.flag_N = (uint8_t)((_t >> 15) & 1); } /* $9329 CMP */
    if (g_cpu.flag_Z) goto L_931F;  /* $932C BEQ */
    func_table_call_jsr(0x85931C); return;  /* $932E JMP (tail) $85931C */
  L_9331:;
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x6A), (uint16_t)(0)); /* $9331 STZ */
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x6C), (uint16_t)(0)); /* $9333 STZ */
    return;            /* $9335 RTS */
}

/* Auto-generated by tools/recomp/autogen.py from $85:84D1
 * entry M=1 X=1 (P=$30). Validate with the diff harness. */
RECOMP_PATCH(smk_8584D1, 0x8584D1) {
    op_rep(0x20);                                  /* $84D1 REP */
    op_inc_dp16(0x64);                             /* $84D3 INC */
    op_sep(0x20);                                  /* $84D5 SEP */
    return;            /* $84D7 RTS */
}

/* Auto-generated by tools/recomp/autogen.py from $81:81C4
 * entry M=0 X=0 (P=$00). Validate with the diff harness. */
RECOMP_PATCH(smk_8181C4, 0x8181C4) {
    { uint16_t _v = (uint16_t)(0x81A8); g_cpu.Y = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $81C4 LDY */
    goto L_81CC;   /* $81C7 BRA */
  L_81CC:;
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x0000 + g_cpu.Y))); g_cpu.X = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $81CC LDX */
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0xB8), (uint16_t)(g_cpu.X)); /* $81CF STX */
    bus_write16(g_cpu.DB, (uint16_t)(0x1EF8 + g_cpu.X), (uint16_t)(0)); /* $81D1 STZ */
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0xC8 + g_cpu.X))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $81D4 LDA */
    bus_write16(g_cpu.DB, 0x0FE0, (uint16_t)(g_cpu.C)); /* $81D6 STA */
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x0002 + g_cpu.Y))); g_cpu.X = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $81D9 LDX */
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0xCE), (uint16_t)(g_cpu.X)); /* $81DC STX */
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x0004 + g_cpu.Y))); g_cpu.X = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $81DE LDX */
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0xCC), (uint16_t)(g_cpu.X)); /* $81E1 STX */
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x0006 + g_cpu.Y))); g_cpu.X = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $81E3 LDX */
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0xBA), (uint16_t)(g_cpu.X)); /* $81E6 STX */
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x0008 + g_cpu.Y))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $81E8 LDA */
    bus_write16(g_cpu.DB, 0x0FE2, (uint16_t)(g_cpu.C)); /* $81EB STA */
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x000A + g_cpu.Y))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $81EE LDA */
    bus_write16(g_cpu.DB, 0x0FE4, (uint16_t)(g_cpu.C)); /* $81F1 STA */
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x000C + g_cpu.Y))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $81F4 LDA */
    bus_write16(g_cpu.DB, 0x0FDC, (uint16_t)(g_cpu.C)); /* $81F7 STA */
    return;            /* $81FA RTS */
}

/* Auto-generated by tools/recomp/autogen.py from $85:B945
 * entry M=0 X=0 (P=$00). Validate with the diff harness. */
RECOMP_PATCH(smk_85B945, 0x85B945) {
    { uint16_t _t = (uint16_t)((g_cpu.Y) + 1); g_cpu.Y = (uint16_t)((_t) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_t) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_t) == 0); } /* $B945 INY */
    { uint16_t _t = (uint16_t)((g_cpu.Y) + 1); g_cpu.Y = (uint16_t)((_t) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_t) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_t) == 0); } /* $B946 INY */
    { uint16_t _t = (uint16_t)((g_cpu.Y) + 1); g_cpu.Y = (uint16_t)((_t) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_t) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_t) == 0); } /* $B947 INY */
    { uint16_t _t = (uint16_t)((g_cpu.Y) + 1); g_cpu.Y = (uint16_t)((_t) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_t) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_t) == 0); } /* $B948 INY */
    return;            /* $B949 RTS */
}

/* Auto-generated by tools/recomp/autogen.py from $81:9587
 * entry M=0 X=0 (P=$00). Validate with the diff harness. */
RECOMP_PATCH(smk_819587, 0x819587) {
    op_phy16();                                    /* $9587 PHY */
    op_sep(0x20);                                  /* $9588 SEP */
    { uint8_t _v = (uint8_t)(bus_read8(g_cpu.DB, (uint16_t)(0x0000 + g_cpu.X))); g_cpu.C = (uint16_t)((g_cpu.C & 0xFF00) | ((_v) & 0xFF)); g_cpu.flag_N = (uint8_t)(((uint8_t)(_v) >> 7) & 1); g_cpu.flag_Z = (uint8_t)((uint8_t)(_v) == 0); } /* $958A LDA */
    bus_write8(g_cpu.DB, 0x211B, (uint8_t)((uint8_t)(g_cpu.C & 0xFF))); /* $958D STA */
    { uint8_t _v = (uint8_t)(bus_read8(g_cpu.DB, (uint16_t)(0x0001 + g_cpu.X))); g_cpu.C = (uint16_t)((g_cpu.C & 0xFF00) | ((_v) & 0xFF)); g_cpu.flag_N = (uint8_t)(((uint8_t)(_v) >> 7) & 1); g_cpu.flag_Z = (uint8_t)((uint8_t)(_v) == 0); } /* $9590 LDA */
    bus_write8(g_cpu.DB, 0x211B, (uint8_t)((uint8_t)(g_cpu.C & 0xFF))); /* $9593 STA */
    { uint8_t _v = (uint8_t)(0x01); g_cpu.C = (uint16_t)((g_cpu.C & 0xFF00) | ((_v) & 0xFF)); g_cpu.flag_N = (uint8_t)(((uint8_t)(_v) >> 7) & 1); g_cpu.flag_Z = (uint8_t)((uint8_t)(_v) == 0); } /* $9596 LDA */
    bus_write8(g_cpu.DB, 0x211C, (uint8_t)((uint8_t)(g_cpu.C & 0xFF))); /* $9598 STA */
    bus_write8(g_cpu.DB, 0x211C, (uint8_t)((uint8_t)(g_cpu.C & 0xFF))); /* $959B STA */
    { uint16_t _v = (uint16_t)(0x3481); g_cpu.Y = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $959E LDY */
    bus_write16(g_cpu.DB, 0x4300, (uint16_t)(g_cpu.Y)); /* $95A1 STY */
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x0002 + g_cpu.X))); g_cpu.Y = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $95A4 LDY */
    bus_write16(g_cpu.DB, 0x4302, (uint16_t)(g_cpu.Y)); /* $95A7 STY */
    { uint8_t _v = (uint8_t)(bus_read8(g_cpu.DB, (uint16_t)(0x0004 + g_cpu.X))); g_cpu.C = (uint16_t)((g_cpu.C & 0xFF00) | ((_v) & 0xFF)); g_cpu.flag_N = (uint8_t)(((uint8_t)(_v) >> 7) & 1); g_cpu.flag_Z = (uint8_t)((uint8_t)(_v) == 0); } /* $95AA LDA */
    bus_write8(g_cpu.DB, 0x4304, (uint8_t)((uint8_t)(g_cpu.C & 0xFF))); /* $95AD STA */
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x0005 + g_cpu.X))); g_cpu.Y = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $95B0 LDY */
    bus_write16(g_cpu.DB, 0x4305, (uint16_t)(g_cpu.Y)); /* $95B3 STY */
    { uint8_t _v = (uint8_t)(0x01); g_cpu.C = (uint16_t)((g_cpu.C & 0xFF00) | ((_v) & 0xFF)); g_cpu.flag_N = (uint8_t)(((uint8_t)(_v) >> 7) & 1); g_cpu.flag_Z = (uint8_t)((uint8_t)(_v) == 0); } /* $95B6 LDA */
    bus_write8(g_cpu.DB, 0x420B, (uint8_t)((uint8_t)(g_cpu.C & 0xFF))); /* $95B8 STA */
    op_rep(0x20);                                  /* $95BB REP */
    op_ply16();                                    /* $95BD PLY */
    return;            /* $95BE RTL */
}

/* Auto-generated by tools/recomp/autogen.py from $81:CBFF
 * entry M=0 X=0 (P=$00). Validate with the diff harness. */
RECOMP_PATCH(smk_81CBFF, 0x81CBFF) {
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0x14 + g_cpu.X))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $CBFF LDA */
    op_pha16();                                    /* $CC01 PHA */
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0x12 + g_cpu.X))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $CC02 LDA */
    op_pha16();                                    /* $CC04 PHA */
    op_phx16();                                    /* $CC05 PHX */
    op_phy16();                                    /* $CC06 PHY */
    { uint16_t _v = (uint16_t)(0x0050); g_cpu.Y = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $CC07 LDY */
    { uint16_t _v = (uint16_t)(0x4000); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $CC0A LDA */
    { uint16_t _a = (uint16_t)(g_cpu.C); uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0xE2 + g_cpu.X))); _a = (uint16_t)(_a & _v); g_cpu.C = (uint16_t)((_a) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_a) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_a) == 0); } /* $CC0D AND */
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0xE2 + g_cpu.X), (uint16_t)(g_cpu.C)); /* $CC0F STA */
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0xA0 + g_cpu.X), (uint16_t)(0)); /* $CC11 STZ */
  L_CC13:;
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x00 + g_cpu.X), (uint16_t)(0)); /* $CC13 STZ */
    { uint16_t _t = (uint16_t)((g_cpu.X) + 1); g_cpu.X = (uint16_t)((_t) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_t) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_t) == 0); } /* $CC15 INX */
    { uint16_t _t = (uint16_t)((g_cpu.X) + 1); g_cpu.X = (uint16_t)((_t) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_t) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_t) == 0); } /* $CC16 INX */
    { uint16_t _t = (uint16_t)((g_cpu.Y) - 1); g_cpu.Y = (uint16_t)((_t) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_t) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_t) == 0); } /* $CC17 DEY */
    if (!g_cpu.flag_Z) goto L_CC13;  /* $CC18 BNE */
    op_ply16();                                    /* $CC1A PLY */
    op_plx16();                                    /* $CC1B PLX */
    op_pla16();                                    /* $CC1C PLA */
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x12 + g_cpu.X), (uint16_t)(g_cpu.C)); /* $CC1D STA */
    op_pla16();                                    /* $CC1F PLA */
    { uint16_t _a = (uint16_t)(g_cpu.C); uint16_t _v = (uint16_t)(0x3FFF); _a = (uint16_t)(_a & _v); g_cpu.C = (uint16_t)((_a) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_a) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_a) == 0); } /* $CC20 AND */
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x14 + g_cpu.X), (uint16_t)(g_cpu.C)); /* $CC23 STA */
    return;            /* $CC25 RTS */
}

/* Auto-generated by tools/recomp/autogen.py from $80:C25A
 * entry M=0 X=0 (P=$00). Validate with the diff harness. */
RECOMP_PATCH(smk_80C25A, 0x80C25A) {
    if (g_cpu.flag_Z) goto L_C266;  /* $C25A BEQ */
    op_phy16();                                    /* $C25C PHY */
    { uint16_t _v = (uint16_t)(0x00B0); g_cpu.Y = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $C25D LDY */
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x04 + g_cpu.X), (uint16_t)(g_cpu.C)); /* $C260 STA */
    func_table_call_jsr(0x80C279);                 /* $C262 JSR $80C279 */
    op_ply16();                                    /* $C265 PLY */
  L_C266:;
    return;            /* $C266 RTL */
}

/* Auto-generated by tools/recomp/autogen.py from $80:C279
 * entry M=0 X=0 (P=$00). Validate with the diff harness. */
RECOMP_PATCH(smk_80C279, 0x80C279) {
    op_phy16();                                    /* $C279 PHY */
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x0002 + g_cpu.Y))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $C27A LDA */
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x02 + g_cpu.Y), (uint16_t)(g_cpu.X)); /* $C27D STX */
    op_tay();                                      /* $C27F TAY */
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x0000 + g_cpu.Y))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $C280 LDA */
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x00 + g_cpu.Y), (uint16_t)(g_cpu.X)); /* $C283 STX */
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x00 + g_cpu.X), (uint16_t)(g_cpu.C)); /* $C285 STA */
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x02 + g_cpu.X), (uint16_t)(g_cpu.Y)); /* $C287 STY */
    op_ply16();                                    /* $C289 PLY */
    return;            /* $C28A RTS */
}

/* Auto-generated by tools/recomp/autogen.py from $85:8FB8
 * entry M=0 X=0 (P=$00). Validate with the diff harness. */
RECOMP_PATCH(smk_858FB8, 0x858FB8) {
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x8FF9 + g_cpu.Y))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8FB8 LDA */
    op_tay();                                      /* $8FBB TAY */
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x22 + g_cpu.X), (uint16_t)(0)); /* $8FBC STZ */
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x0000 + g_cpu.Y))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8FBE LDA */
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x18 + g_cpu.X), (uint16_t)(g_cpu.C)); /* $8FC1 STA */
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x0002 + g_cpu.Y))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8FC3 LDA */
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x1C + g_cpu.X), (uint16_t)(g_cpu.C)); /* $8FC6 STA */
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x0004 + g_cpu.Y))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8FC8 LDA */
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x2A + g_cpu.X), (uint16_t)(g_cpu.C)); /* $8FCB STA */
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x0006 + g_cpu.Y))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8FCD LDA */
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x92 + g_cpu.X), (uint16_t)(g_cpu.C)); /* $8FD0 STA */
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x0008 + g_cpu.Y))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8FD2 LDA */
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x44 + g_cpu.X), (uint16_t)(g_cpu.C)); /* $8FD5 STA */
    return;            /* $8FD7 RTS */
}

